CREATE DATABASE IF NOT EXISTS cysvet_prod
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'cysvet_app'@'%' IDENTIFIED BY 'CHANGE_ME_STRONG_PASSWORD';
ALTER USER 'cysvet_app'@'%' IDENTIFIED BY 'CHANGE_ME_STRONG_PASSWORD';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES
    ON cysvet_prod.* TO 'cysvet_app'@'%';

FLUSH PRIVILEGES;
