spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cysvet?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: ${JWT_SECRET:cysvet-super-secret-key-for-development-only-change-me}
